Repository Redocly/redocly-cli, pull requests merged in 2022-03, with the labels that each got.

#597 hotfix: do not crash on empty redocly.yaml
  packages/core/src/config/config.ts
  packages/core/src/config/load.ts
Labels: Type: Bug

#594 feat: Mock Server config
  packages/core/src/types/redocly-yaml.ts
Labels: deploy_s3_sandbox

#580 Update commands/index.md
  docs/commands/index.md
Labels: documentation

#578 Update installation.md
  docs/installation.md
Labels: documentation

#576 Update index.md
  docs/index.md
Labels: documentation

#579 Create openapi-starter.md
  docs/openapi-starter.md
Labels: documentation

#577 Update quickstart.md
  docs/quickstart.md
Labels: documentation
