Repository Redocly/redocly-cli, pull requests merged in 2024-10, with the labels that each got.

#1747 fix: bundle externalValue with relative reference in examples object
  .changeset/little-pears-sniff.md
  __tests__/bundle/bundle-external-value/external-value.json
  __tests__/bundle/bundle-external-value/redocly.yaml
  __tests__/bundle/bundle-external-value/snapshot.js
  __tests__/bundle/bundle-external-value/test-success.yaml
  __tests__/bundle/bundle-external-value/test-wrong-examples.yaml
  packages/core/src/bundle.ts
  packages/core/src/resolve.ts
  packages/core/src/rules/oas3/__tests__/fixtures/external-value.yaml
  packages/core/src/rules/oas3/__tests__/no-invalid-media-type-examples.test.ts
Labels: deploy_s3_sandbox

#1753 chore: delay _importDynamic initialization
  packages/core/src/config/config-resolvers.ts
Labels: deploy_s3_sandbox, No Changeset Needed

#1666 fix: wrong discriminator mapping when bundling with derefernce
  .changeset/proud-chairs-lie.md
  __tests__/bundle/discriminator-mapping/bar.yaml
  __tests__/bundle/discriminator-mapping/foo.yaml
  __tests__/bundle/discriminator-mapping/main.yaml
  __tests__/bundle/discriminator-mapping/redocly.yaml
  __tests__/bundle/discriminator-mapping/snapshot.js
  __tests__/commands.test.ts
  packages/core/src/bundle.ts
Labels: deploy_s3_sandbox

#1781 chore: update benchmarks, coverage threshold; improve types and names
  benchmark/chart.mjs
  benchmark/make-test-command.sh
  benchmark/package.json
  jest.config.js
  packages/core/src/bundle.ts
  packages/core/src/resolve.ts
Labels: No Changeset Needed
