Repository Redocly/redocly-cli, pull requests merged in 2024-09, with the labels that each got.

#1676 chore: send user-agent to Reunite
  packages/cli/src/__tests__/fetch-with-timeout.test.ts
  packages/cli/src/cms/api/__tests__/api.client.test.ts
  packages/cli/src/cms/api/api-client.ts
  packages/cli/src/cms/commands/__tests__/push-status.test.ts
  packages/cli/src/cms/commands/__tests__/push.test.ts
  packages/cli/src/cms/commands/__tests__/utils.test.ts
  packages/cli/src/cms/commands/push-status.ts
  packages/cli/src/cms/commands/push.ts
  packages/cli/src/cms/commands/utils.ts
  packages/cli/src/utils/fetch-with-timeout.ts
  packages/cli/src/utils/miscellaneous.ts
  packages/cli/src/utils/update-version-notifier.ts
Labels: deploy_s3_sandbox, No Changeset Needed

#1708 feat: add output as a per-API configuration option
  .changeset/afraid-melons-sparkle.md
  docs/commands/bundle.md
  docs/configuration/reference/apis.md
  packages/cli/src/__tests__/commands/bundle.test.ts
  packages/cli/src/__tests__/utils.test.ts
  packages/cli/src/commands/bundle.ts
  packages/cli/src/types.ts
  packages/cli/src/utils/__mocks__/miscellaneous.ts
  packages/cli/src/utils/miscellaneous.ts
  packages/core/src/config/types.ts
  packages/core/src/utils.ts
Labels: deploy_s3_sandbox

#1717 fix: bundling multiple files specified as CLI arguments
  .changeset/late-readers-design.md
  docs/commands/bundle.md
  packages/cli/src/__tests__/commands/bundle.test.ts
  packages/cli/src/commands/bundle.ts
  packages/cli/src/utils/miscellaneous.ts
Labels: deploy_s3_sandbox

#1714 docs: updating translate doc with project-dir option
  docs/commands/translate.md
Labels: Type: Docs

#1719 fix: deprecated warning for punycode package
  .changeset/orange-apricots-drop.md
  package-lock.json
  packages/core/package.json
Labels: deploy_s3_sandbox

#1703 docs: add eject command page
  docs/commands/eject.md
  docs/commands/index.md
  docs/commands/preview.md
  docs/sidebars.yaml
  packages/cli/src/index.ts
Labels: Type: Docs, No Changeset Needed
