Repository Redocly/redocly-cli, pull requests merged in 2024-07, with the labels that each got.

#1601 feat: lint arazzo test descriptions
  .changeset/green-worms-vanish.md
  __tests__/bundle/bundle-arazzo-valid-test-description/museum.yaml
  __tests__/bundle/bundle-arazzo-valid-test-description/parameter.yaml
  __tests__/bundle/bundle-arazzo-valid-test-description/request-body.yaml
  __tests__/bundle/bundle-arazzo-valid-test-description/snapshot.js
  __tests__/check-config/wrong-config-type-extensions-in-assertions/snapshot.js
  __tests__/commands.test.ts
  __tests__/lint-config/invalid-config-assertation-config-type/snapshot.js
  __tests__/lint-config/invalid-lint-config-severity/snapshot.js
  __tests__/lint/arazzo-not-valid-test-description/museum.yaml
  __tests__/lint/arazzo-not-valid-test-description/snapshot.js
  __tests__/lint/arazzo-type-extensions-with-plugin/museum.yaml
  __tests__/lint/arazzo-type-extensions-with-plugin/plugins/type-extention.js
  __tests__/lint/arazzo-type-extensions-with-plugin/redocly.yaml
  __tests__/lint/arazzo-type-extensions-with-plugin/snapshot.js
  __tests__/lint/arazzo-valid-test-description/museum.yaml
  __tests__/lint/arazzo-valid-test-description/snapshot.js
  docs/commands/lint.md
  package-lock.json
  packages/cli/src/__tests__/utils.test.ts
  packages/cli/src/index.ts
  packages/cli/src/utils/miscellaneous.ts
  packages/core/package.json
  packages/core/src/bundle.ts
  packages/core/src/config/__tests__/__snapshots__/config-resolvers.test.ts.snap
  packages/core/src/config/__tests__/__snapshots__/config.test.ts.snap
  packages/core/src/config/__tests__/config.test.ts
  packages/core/src/config/all.ts
  packages/core/src/config/builtIn.ts
  packages/core/src/config/config-resolvers.ts
  packages/core/src/config/config.ts
  packages/core/src/config/minimal.ts
  packages/core/src/config/recommended-strict.ts
  packages/core/src/config/recommended.ts
  packages/core/src/config/types.ts
  packages/core/src/config/utils.ts
  packages/core/src/decorators/arazzo/index.ts
  packages/core/src/decorators/async2/index.ts
  packages/core/src/index.ts
  packages/core/src/oas-types.ts
  packages/core/src/rules/arazzo/index.ts
  packages/core/src/rules/common/spec.ts
  packages/core/src/types/arazzo.ts
  packages/core/src/types/redocly-yaml.ts
  packages/core/src/typings/arazzo.ts
  packages/core/src/visitors.ts
Labels: deploy_s3_sandbox

#1621 fix: arazzo parameter schema update
  packages/core/src/types/arazzo.ts
Labels: No Changeset Needed

#1626 chore: use dequal instead of lodash.isequal
  packages/cli/src/commands/join.ts
  packages/cli/src/commands/split/index.ts
  packages/core/src/bundle.ts
  packages/core/src/utils.ts
Labels: deploy_s3_sandbox, No Changeset Needed

#1630 feat: export more individual types for arazzo
  packages/core/src/types/arazzo.ts
  packages/core/src/typings/arazzo.ts
Labels: No Changeset Needed

#1633 fix: update arazzo types
  __tests__/check-config/wrong-config-type-extensions-in-assertions/snapshot.js
  __tests__/lint-config/invalid-config-assertation-config-type/snapshot.js
  packages/core/src/types/arazzo.ts
Labels: No Changeset Needed

#1617 chore: re-enable the Reference Docs options in the theme.openapi config
  .changeset/clever-fans-cross.md
  .gitignore
  __tests__/build-docs/build-docs-with-config-option/snapshot.js
  __tests__/lint-config/config-structure/.redocly.yaml
  __tests__/lint-config/config-structure/snapshot.js
  __tests__/lint-config/config-with-refs-extended/snapshot.js
  __tests__/lint-config/config-with-refs-extended/theme-openapi.yaml
  __tests__/lint-config/config-with-refs/snapshot.js
  __tests__/lint-config/config-with-refs/theme-openapi.yaml
  package-lock.json
  packages/cli/package.json
  packages/cli/src/cms/commands/push.ts
  packages/cli/src/commands/lint.ts
  packages/cli/src/commands/push.ts
  packages/cli/src/utils/miscellaneous.ts
  packages/core/package.json
  packages/core/src/__tests__/lint.test.ts
  packages/core/src/config/load.ts
  packages/core/src/rules/common/no-invalid-schema-examples.ts
  packages/core/src/rules/common/path-segment-plural.ts
  packages/core/src/utils.ts
Labels: deploy_s3_sandbox

#1642 docs: add a guide for linting Arazzo files
  docs/guides/images/museum-arazzo-lint.png
  docs/guides/index.md
  docs/guides/lint-arazzo.md
  docs/sidebars.yaml
Labels: Type: Docs

#1640 chore: update typescript to v5.5.3
  jest.config.js
  package-lock.json
  package.json
  packages/cli/package.json
  packages/core/package.json
  packages/core/src/bundle.ts
  packages/core/src/config/rules.ts
  packages/core/src/decorators/common/remove-x-internal.ts
  packages/core/src/lint.ts
  packages/core/src/oas-types.ts
  packages/core/src/rules/arazzo/index.ts
  packages/core/src/rules/async2/index.ts
  packages/core/src/rules/async3/index.ts
  packages/core/src/rules/common/assertions/index.ts
  packages/core/src/rules/oas2/index.ts
  packages/core/src/rules/oas3/index.ts
  tsconfig.json
Labels: No Changeset Needed
