Repository Redocly/redocly-cli, pull requests merged in 2024-04, with the labels that each got.

#1512 chore: update core version in config
  package-lock.json
  packages/core/package.json
Labels: No Changeset Needed

#1526 docs: remove 2024 gsod proposal
  docs/gsod/2024/proposal.md
Labels: Type: Docs

#1527 fix: resolve config extensions using only one resolver
  .changeset/many-steaks-hope.md
  packages/core/src/bundle.ts
  packages/core/src/config/__tests__/config-resolvers.test.ts
  packages/core/src/config/__tests__/fixtures/load-external.yaml
  packages/core/src/config/__tests__/load.test.ts
  packages/core/src/config/config-resolvers.ts
  packages/core/src/config/load.ts
Labels: deploy_s3_sandbox

#1481 feat: update push and push-status commands
  .changeset/heavy-swans-sin.md
  CONTRIBUTING.md
  package.json
  packages/cli/src/cms/api/types.ts
  packages/cli/src/cms/commands/__tests__/push-status.test.ts
  packages/cli/src/cms/commands/__tests__/push.test.ts
  packages/cli/src/cms/commands/__tests__/utils.test.ts
  packages/cli/src/cms/commands/push-status.ts
  packages/cli/src/cms/commands/push.ts
  packages/cli/src/cms/commands/utils.ts
  packages/cli/src/index.ts
  packages/cli/src/wrapper.ts
  packages/core/src/format/format.ts
  packages/core/src/index.ts
  packages/core/src/utils.ts
Labels: deploy_s3_sandbox
