Repository Redocly/redocly-cli, pull requests merged in 2025-03, with the labels that each got.

#1973 chore: update S3 sandbox deploymet pipeline
  .github/workflows/deploy-s3-sandbox.yaml
Labels: deploy_s3_sandbox

#1980 fix: validate nullable oas3 example correctly
  .changeset/rich-falcons-act.md
  packages/core/src/rules/common/__tests__/no-invalid-schema-examples.test.ts
  packages/core/src/rules/common/no-invalid-schema-examples.ts
  packages/core/src/rules/oas2/index.ts
  packages/core/src/rules/oas3/index.ts
Labels: deploy_s3_sandbox

#1993 chore: change snapshot release
  .github/workflows/require-changeset.yaml
  .github/workflows/snapshot-pr.yaml
  .github/workflows/snapshot-release.yaml
  package-lock.json
Labels: snapshot

#1995 docs: update readme in openapi-core
  packages/core/README.md
Labels: no changeset needed

#1997 docs: update command option in examples
  .changeset/spotty-maps-grab.md
  docs/commands/generate-arazzo.md
Labels: no changeset needed

#2001 docs(respect): add respect commands to cli commands sidebar
  docs/sidebars.yaml
Labels: no changeset needed

#2010 chore: improve clearargs
  packages/cli/src/__tests__/utils.test.ts
  packages/cli/src/utils/miscellaneous.ts
Labels: no changeset needed

#2003 feat(respect): introduce global execution timeout-timer
  .changeset/silent-suits-kiss.md
  __tests__/respect/consider-severity-in-next-step-execution/__snapshots__/consider-severity-in-next-step-execution.test.ts.snap
  __tests__/respect/inputs-with-cli-and-env/__snapshots__/inputs-with-cli-and-env.test.ts.snap
  __tests__/respect/mask-input-secrets/__snapshots__/mask-input-secrets.test.ts.snap
  __tests__/respect/max-steps/__snapshots__/max-steps.test.ts.snap
  __tests__/respect/museum-api-with-errors.yaml
  __tests__/respect/museum-api.yaml
  __tests__/respect/outputs-access-syntax-variations/__snapshots__/outputs-access-syntax-variations.test.ts.snap
  __tests__/respect/replacements/__snapshots__/replacements.test.ts.snap
  __tests__/respect/reusable-components/__snapshots__/reusable-components.test.ts.snap
  __tests__/respect/severity-error-level/__snapshots__/severity-error-level.test.ts.snap
  __tests__/respect/severity-off-level/__snapshots__/severity-off-level.test.ts.snap
  __tests__/respect/severity-warn-level/__snapshots__/severity-warn-level.test.ts.snap
  __tests__/smoke/pre-built/redoc.html
  packages/respect-core/src/consts.ts
  packages/respect-core/src/handlers/run.ts
  packages/respect-core/src/modules/__tests__/flow-runner/run-step.test.ts
  packages/respect-core/src/modules/__tests__/timeout-timer/timer.test.ts
  packages/respect-core/src/modules/checks/checks.ts
  packages/respect-core/src/modules/checks/severity.ts
  packages/respect-core/src/modules/cli-output/display-errors.ts
  packages/respect-core/src/modules/cli-output/json-logs.ts
  packages/respect-core/src/modules/flow-runner/run-step.ts
  packages/respect-core/src/modules/flow-runner/runner.ts
  packages/respect-core/src/modules/timeout-timer/timer.ts
  packages/respect-core/src/types.ts
  packages/respect-core/src/utils/api-fetcher.ts
Labels: snapshot

#2016 chore: update benchmark
  benchmark/package.json
Labels: no changeset needed

#2026 docs: add latest to all npx redocly cli commands
  README.md
  docs/commands/generate-arazzo.md
  docs/commands/index.md
  docs/commands/push.md
  docs/commands/respect.md
  docs/guides/hide-specification-extensions.md
  docs/guides/replace-servers-url.md
  docs/installation.md
Labels: no changeset needed

#2029 refactor: fix __dirname and package.json import issues
  .github/workflows/smoke-plugins.yaml
  .github/workflows/smoke.yaml
  __tests__/smoke/pre-built/redoc.html
  packages/cli/src/__tests__/commands/lint.test.ts
  packages/cli/src/commands/build-docs/index.ts
  packages/cli/src/commands/build-docs/utils.ts
  packages/cli/src/index.ts
  packages/cli/src/otel.ts
  packages/cli/src/utils/assert-node-version.ts
  packages/cli/src/utils/miscellaneous.ts
  packages/cli/src/utils/package.ts
  packages/cli/src/utils/update-version-notifier.ts
  packages/cli/src/wrapper.ts
  packages/core/src/benchmark/benches/lint-with-many-rules.bench.ts
  packages/core/src/config/config-resolvers.ts
  packages/core/src/format/format.ts
  packages/core/src/index.ts
  packages/respect-core/src/modules/config-parser/parse-request-body.ts
  packages/respect-core/src/modules/flow-runner/get-test-description-from-file.ts
  packages/respect-core/src/utils/har-logs/create-har-log.ts
  packages/respect-core/src/utils/package.ts
Labels: no changeset needed
