Repository Redocly/redocly-cli, pull requests merged in 2025-02, with the labels that each got.

#1883 chore: reduce recommended npm version
  package-lock.json
  package.json
  packages/cli/package.json
  packages/core/package.json
Labels: no changeset needed

#1882 docs(all): clarifies what is overridden on a per-api basis
  docs/configuration/apis.md
Labels: Type: Docs

#1909 chore: change telemetry provider
  jest.config.js
  package-lock.json
  packages/cli/package.json
  packages/cli/src/otel.ts
  packages/cli/src/utils/miscellaneous.ts
Labels: deploy_s3_sandbox, no changeset needed

#1876 feat(rules): update `operation-tag-defined` rule
  .changeset/tasty-cougars-dress.md
  __tests__/lint/turn-on-all-rules/snapshot.js
  docs/rules/oas/operation-tag-defined.md
  packages/core/src/rules/common/__tests__/operation-tag-defined.test.ts
  packages/core/src/rules/common/operation-tag-defined.ts
Labels: deploy_s3_sandbox

#1918 fix: cookies from workflows and step are not set to the request
  packages/respect-core/src/modules/__tests__/config-parcer/map-header-params-and-cookie-to-object.test.ts
  packages/respect-core/src/modules/__tests__/flow-runner/prepare-request.test.ts
  packages/respect-core/src/modules/config-parser/index.ts
  packages/respect-core/src/modules/config-parser/map-header-params-and-cookie-to-object.ts
  packages/respect-core/src/modules/flow-runner/prepare-request.ts
  packages/respect-core/src/utils/api-fetcher.ts
Labels: no changeset needed

#1920 chore: update respect command handler
  packages/cli/src/index.ts
  packages/respect-core/src/handlers/run.ts
  packages/respect-core/src/modules/__tests__/test-config-generator/generate-test-config.test.ts
  packages/respect-core/src/modules/flow-runner/runner.ts
Labels: no changeset needed

#1924 chore: improve performance
  CONTRIBUTING.md
  benchmark/package.json
  packages/cli/src/index.ts
Labels: no changeset needed

#1925 fix: kebab case command options & mtls path & remove residensy
  jest.config.js
  packages/cli/src/index.ts
  packages/respect-core/src/handlers/generate.ts
  packages/respect-core/src/handlers/run.ts
  packages/respect-core/src/index.ts
  packages/respect-core/src/modules/__tests__/flow-runner/context/create-test-context.test.ts
  packages/respect-core/src/modules/__tests__/test-config-generator/generate-test-config.test.ts
  packages/respect-core/src/modules/flow-runner/context/create-test-context.ts
  packages/respect-core/src/modules/flow-runner/runner.ts
  packages/respect-core/src/modules/test-config-generator/generate-test-config.ts
  packages/respect-core/src/types.ts
  packages/respect-core/src/utils/__tests__/get-reunite-url.test.ts
  packages/respect-core/src/utils/__tests__/mtls/resolve-mtls-certificates.test.ts
  packages/respect-core/src/utils/exit-with-error.ts
  packages/respect-core/src/utils/get-reunite-url.ts
  packages/respect-core/src/utils/mtls/resolve-mtls-certificates.ts
Labels: no changeset needed

#1926 chore: cleanup resources folder
  __tests__/smoke/pre-split/museum/openapi.yaml
  resources/museum-api-test.yaml
  resources/museum-api.arazzo.yaml
  resources/museum-api.yaml
  resources/museum-tickets.arazzo.yaml
  resources/museum-tickets.yaml
  resources/museum.yaml
Labels: no changeset needed

#1929 chore: update package lock
  package-lock.json
  packages/respect-core/package.json
Labels: no changeset needed

#1930 feat: removed extended option from generate-arazzo command
  packages/cli/src/index.ts
  packages/respect-core/src/handlers/generate.ts
  packages/respect-core/src/modules/__tests__/test-config-generator/generate-test-config.test.ts
  packages/respect-core/src/modules/test-config-generator/generate-test-config.ts
Labels: no changeset needed

#1932 chore: refactor types, descriptions and names
  __tests__/helpers.ts
  docs/usage-data.md
  packages/cli/src/index.ts
  packages/cli/src/types.ts
  packages/respect-core/src/handlers/generate.ts
  packages/respect-core/src/handlers/run.ts
  packages/respect-core/src/modules/__tests__/arazzo-description-generator/cleanup-test-description.test.ts
  packages/respect-core/src/modules/__tests__/arazzo-description-generator/generate-arazzo-description.test.ts
  packages/respect-core/src/modules/__tests__/arazzo-description-generator/generate-example-value.test.ts
  packages/respect-core/src/modules/__tests__/arazzo-description-generator/generate-test-data-from-json-schema.test.ts
  packages/respect-core/src/modules/arazzo-description-generator/cleanup-test-description.ts
  packages/respect-core/src/modules/arazzo-description-generator/generate-arazzo-description.ts
  packages/respect-core/src/modules/arazzo-description-generator/generate-example-value.ts
  packages/respect-core/src/modules/arazzo-description-generator/generate-test-data-from-json-schema.ts
  packages/respect-core/src/modules/arazzo-description-generator/index.ts
  packages/respect-core/src/modules/description-parser/get-request-data-from-openapi.ts
  packages/respect-core/src/modules/flow-runner/context/create-test-context.ts
Labels: no changeset needed

#1935 chore: improve tests
  .github/workflows/performance.yaml
  .github/workflows/smoke-plugins.yaml
  .github/workflows/smoke-rebilly.yaml
  .github/workflows/tests.yaml
  __tests__/smoke-rebilly/__snapshots__/rebilly.smoke.ts.snap
  __tests__/smoke-rebilly/rebilly-description.yaml
  __tests__/smoke-rebilly/rebilly.smoke.ts
  __tests__/smoke-rebilly/rebilly.yaml
  package.json
  packages/respect-core/jest.config.unit.js
Labels: no changeset needed

#1936 feat: resolve server url
  jest.config.js
  packages/respect-core/src/modules/__tests__/flow-runner/get-server-url.test.ts
  packages/respect-core/src/modules/__tests__/flow-runner/prepare-request.test.ts
  packages/respect-core/src/modules/description-parser/get-request-data-from-openapi.ts
  packages/respect-core/src/modules/flow-runner/get-server-url.ts
  packages/respect-core/src/modules/flow-runner/prepare-request.ts
  packages/respect-core/src/utils/api-fetcher.ts
Labels: no changeset needed

#1938 chore: implement new json output and improve counting of steps
  __tests__/respect/reusable-components/__snapshots__/reusable-components.test.ts.snap
  __tests__/respect/server-override-with-console-parameters/__snapshots__/server-override-with-console-parameters.test.ts.snap
  __tests__/respect/step-on-failure-type-end-action/__snapshots__/step-on-failure-type-end-action.test.ts.snap
  __tests__/respect/step-on-success-type-end-action/__snapshots__/step-on-success-type-end-action.test.ts.snap
  __tests__/respect/workflow-failure-actions/__snapshots__/workflow-failure-actions.test.ts.snap
  __tests__/respect/workflow-success-actions/__snapshots__/workflow-success-actions.test.ts.snap
  jest.config.js
  packages/respect-core/src/handlers/run.ts
  packages/respect-core/src/index.ts
  packages/respect-core/src/modules/__tests__/flow-runner/context/__snapshots__/create-test-context.test.ts.snap
  packages/respect-core/src/modules/__tests__/flow-runner/context/create-test-context.test.ts
  packages/respect-core/src/modules/__tests__/flow-runner/run-step.test.ts
  packages/respect-core/src/modules/__tests__/flow-runner/runner/create-workflow-runner.test.ts
  packages/respect-core/src/modules/__tests__/flow-runner/runner/resolve-workflow-context.test.ts
  packages/respect-core/src/modules/__tests__/flow-runner/runner/run-test-file.test.ts
  packages/respect-core/src/modules/cli-output/calculate-tests-passed.ts
  packages/respect-core/src/modules/cli-output/display-errors.ts
  packages/respect-core/src/modules/cli-output/display-files-summary-table.ts
  packages/respect-core/src/modules/cli-output/display-summary.ts
  packages/respect-core/src/modules/cli-output/json-logs.ts
  packages/respect-core/src/modules/flow-runner/call-api-and-analyze-results.ts
  packages/respect-core/src/modules/flow-runner/context/create-test-context.ts
  packages/respect-core/src/modules/flow-runner/run-step.ts
  packages/respect-core/src/modules/flow-runner/runner.ts
  packages/respect-core/src/types.ts
  packages/respect-core/src/utils/api-fetcher.ts
Labels: no changeset needed

#1937 chore: use json server test
  __tests__/respect/local-json-server/__snapshots__/local-json-server.test.ts.snap
  __tests__/respect/local-json-server/local-json-server.test.ts
  jest.config.js
  package-lock.json
  package.json
  packages/cli/package.json
  packages/core/package.json
  packages/respect-core/.dockerignore
  packages/respect-core/.env.example
  packages/respect-core/.gitignore
  packages/respect-core/Dockerfile
  packages/respect-core/jest.config.js
  packages/respect-core/package.json
Labels: no changeset needed

#1941 chore: improve performance
  jest.config.js
  packages/cli/src/utils/miscellaneous.ts
Labels: no changeset needed

#1943 feat: changes to success criteria checks display
  __tests__/respect/case-insensitive-headers/__snapshots__/case-insensitive-headers.test.ts.snap
  __tests__/respect/cat-fact-api/__snapshots__/cat-fact-api.test.ts.snap
  __tests__/respect/free-apis/__snapshots__/free-apis.test.ts.snap
  __tests__/respect/implicit/__snapshots__/implicit.test.ts.snap
  __tests__/respect/inputs-with-cli-and-env/__snapshots__/inputs-with-cli-and-env.test.ts.snap
  __tests__/respect/local-json-server/__snapshots__/local-json-server.test.ts.snap
  __tests__/respect/mask-input-secrets/__snapshots__/mask-input-secrets.test.ts.snap
  __tests__/respect/outputs-access-syntax-variations/__snapshots__/outputs-access-syntax-variations.test.ts.snap
  __tests__/respect/reusable-components/__snapshots__/reusable-components.test.ts.snap
  __tests__/respect/severity-error-level/__snapshots__/severity-error-level.test.ts.snap
  __tests__/respect/severity-off-level/__snapshots__/severity-off-level.test.ts.snap
  __tests__/respect/severity-warn-level/__snapshots__/severity-warn-level.test.ts.snap
  __tests__/respect/step-on-failure-type-end-action/__snapshots__/step-on-failure-type-end-action.test.ts.snap
  __tests__/respect/step-on-success-type-end-action/__snapshots__/step-on-success-type-end-action.test.ts.snap
  __tests__/respect/workflow-failure-actions/__snapshots__/workflow-failure-actions.test.ts.snap
  __tests__/respect/workflow-success-actions/__snapshots__/workflow-success-actions.test.ts.snap
  __tests__/smoke-rebilly/__snapshots__/rebilly.smoke.ts.snap
  __tests__/smoke-rebilly/rebilly.smoke.ts
  packages/respect-core/src/modules/__tests__/flow-runner/__snapshots__/run-step.test.ts.snap
  packages/respect-core/src/modules/__tests__/flow-runner/run-step.test.ts
  packages/respect-core/src/modules/__tests__/flow-runner/runner/run-test-file.test.ts
  packages/respect-core/src/modules/__tests__/flow-runner/schema/schema-checker.test.ts
  packages/respect-core/src/modules/__tests__/flow-runner/success-criteria/check-success-criteria.test.ts
  packages/respect-core/src/modules/cli-output/calculate-tests-passed.ts
  packages/respect-core/src/modules/cli-output/display-checks.ts
  packages/respect-core/src/modules/cli-output/display-errors.ts
  packages/respect-core/src/modules/cli-output/json-logs.ts
  packages/respect-core/src/modules/flow-runner/call-api-and-analyze-results.ts
  packages/respect-core/src/modules/flow-runner/run-step.ts
  packages/respect-core/src/modules/flow-runner/runner.ts
  packages/respect-core/src/modules/flow-runner/schema/schema-checker.ts
  packages/respect-core/src/modules/flow-runner/success-criteria/check-success-criteria.ts
  packages/respect-core/src/types.ts
  packages/respect-core/src/utils/__tests__/cli-outputs.test.ts
Labels: no changeset needed

#1946 chore: rename cli rules
  docs/changelog.md
  docs/guides/lint-arazzo.md
  docs/rules/built-in-rules.md
  docs/rules/respect/no-criteria-xpath.md
  docs/rules/respect/respect-supported-versions.md
  docs/rules/ruleset-templates.md
  docs/rules/spec-ruleset.md
  docs/sidebars.yaml
  packages/core/CHANGELOG.md
  packages/core/src/config/__tests__/__snapshots__/config-resolvers.test.ts.snap
  packages/core/src/config/all.ts
  packages/core/src/config/minimal.ts
  packages/core/src/config/recommended-strict.ts
  packages/core/src/config/recommended.ts
  packages/core/src/config/spec.ts
  packages/core/src/rules/arazzo/__tests__/no-criteria-xpath.test.ts
  packages/core/src/rules/arazzo/__tests__/respect-supported-versions.test.ts
  packages/core/src/rules/arazzo/index.ts
  packages/core/src/rules/respect/no-criteria-xpath.ts
  packages/core/src/rules/respect/respect-supported-versions.ts
  packages/core/src/types/redocly-yaml.ts
  packages/core/src/typings/arazzo.ts
  packages/respect-core/src/modules/__tests__/flow-runner/run-step.test.ts
  packages/respect-core/src/modules/flow-runner/get-test-description-from-file.ts
Labels: no changeset needed

#1949 fix: server selection by index
  packages/respect-core/src/modules/__tests__/flow-runner/get-server-url.test.ts
  packages/respect-core/src/modules/flow-runner/get-server-url.ts
Labels: no changeset needed

#1950 fix: replacement value evaluation
  __tests__/respect/inputs-with-cli-and-env/__snapshots__/inputs-with-cli-and-env.test.ts.snap
  __tests__/respect/inputs-with-cli-and-env/inputs-with-cli-and-env.yaml
  __tests__/respect/local-json-server/local-json-server.test.ts
  __tests__/respect/replacements/__snapshots__/replacements.test.ts.snap
  __tests__/respect/replacements/museum-api.yaml
  __tests__/respect/replacements/replacements.arazzo.yaml
  __tests__/respect/replacements/replacements.test.ts
  __tests__/respect/severity-warn-level/__snapshots__/severity-warn-level.test.ts.snap
  __tests__/respect/severity-warn-level/severity-level.yaml
  __tests__/respect/step-on-failure-type-end-action/step-on-failure-type-end-action.test.ts
  package-lock.json
  packages/core/src/rules/arazzo/requestBody-replacements-unique.ts
  packages/respect-core/src/modules/__tests__/config-parser/handle-request-body-replacements.test.ts
  packages/respect-core/src/modules/__tests__/config-parser/parse-request-body.test.ts
  packages/respect-core/src/modules/config-parser/handle-request-body-replacements.ts
  packages/respect-core/src/modules/config-parser/parse-request-body.ts
  packages/respect-core/src/modules/flow-runner/prepare-request.ts
Labels: no changeset needed

#1952 chore: remove es build
  package-lock.json
  packages/core/src/rules/oas3/__tests__/no-invalid-media-type-examples.test.ts
  packages/respect-core/bin/e2e.sh
  packages/respect-core/bin/index.js
  packages/respect-core/esbuild.cjs
  packages/respect-core/examples/museum-api/museum-api-test.yaml
  packages/respect-core/examples/museum-api/museum-api-with-errors.yaml
  packages/respect-core/examples/museum-api/museum-api.yaml
  packages/respect-core/examples/museum-api/museum-tickets.yaml
  packages/respect-core/package.json
Labels: no changeset needed

#1960 chore: add @redocly/config to @redocly/cli dependencies
  package-lock.json
  packages/cli/package.json
Labels: no changeset needed

#1964 fix: add node types to tsconfig in respect-core
  packages/respect-core/tsconfig.json
Labels: no changeset needed, snapshot
