Repository Redocly/redocly-cli, pull requests merged in 2025-08, with the labels that each got.

#2245 fix(respect): binary data is destroyed when consumed with text
  .changeset/unlucky-feet-give.md
  packages/cli/src/commands/respect/index.ts
  packages/cli/src/utils/__tests__/json-stringify-with-array-buffer.test.ts
  packages/cli/src/utils/json-stringify-with-array-buffer.ts
  packages/core/src/index.ts
  packages/respect-core/src/modules/__tests__/logger-output/mask-secrets.test.ts
  packages/respect-core/src/modules/logger-output/display-checks.ts
  packages/respect-core/src/modules/logger-output/helpers.ts
  packages/respect-core/src/modules/logger-output/mask-secrets.ts
  packages/respect-core/src/modules/logger-output/verbose-logs.ts
  packages/respect-core/src/modules/runtime-expressions/evaluate.ts
  packages/respect-core/src/utils/__tests__/deep-copy.test.ts
  packages/respect-core/src/utils/__tests__/is-binary-content-type.test.ts
  packages/respect-core/src/utils/api-fetcher.ts
  packages/respect-core/src/utils/binary-content-type-checker.ts
  packages/respect-core/src/utils/deep-copy.ts
  packages/respect-core/src/utils/time.ts
Labels: snapshot

#2249 fix: pass externalRefResolver to nested workflow context
  .changeset/quiet-experts-hope.md
  packages/respect-core/src/modules/__tests__/flow-runner/runner/resolve-workflow-context.test.ts
  packages/respect-core/src/modules/flow-runner/runner.ts
Labels: snapshot

#2271 chore: export AsyncAPI types externally
  packages/core/src/bundle.ts
  packages/core/src/dequal.ts
  packages/core/src/index.ts
  packages/core/src/utils.ts
Labels: no changeset needed

#2272 fix: respect reset execution timeout timer on each run
  packages/respect-core/src/run.ts
Labels: no changeset needed, snapshot
